language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - shamin616@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - cd docs && yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/public
  target-branch: gh-pages
  on:
    branch: master
